/* 04-review.js
   seal/re-seal/eternal, REVIEW_LADDER scheduling, due lists, RANKS
   Extracted verbatim from index.html lines 3251-3310 by T2. */
/* =========================================================
   REVIEW ENGINE — seals fade, re-seals climb the ladder
   ========================================================= */
function isEternal(p){ return p.sealed && (p.reviewLevel||0) >= REVIEW_LADDER.length; }
function sealVerse(p){
  const now = Date.now();
  p.sealed = true; p.stage = 4;
  p.sealedAt = now; p.reviewLevel = 0; p.reviews = 0;
  p.nextReviewAt = now + REVIEW_LADDER[0]*DAY;
}
function resealVerse(p){
  const now = Date.now();
  const overdueDays = (now - (p.nextReviewAt||now)) / DAY;
  let lvl = p.reviewLevel || 0;
  if(overdueDays > 10) lvl = Math.max(0, lvl - 1);   // cracked seals slip a rung
  else lvl = Math.min(REVIEW_LADDER.length, lvl + 1);
  p.reviewLevel = lvl;
  p.reviews = (p.reviews||0) + 1;
  p.lastReviewAt = now;
  state.resealsTotal = (state.resealsTotal||0) + 1;
  const eternal = lvl >= REVIEW_LADDER.length;
  p.nextReviewAt = eternal ? now + 365*DAY*50 : now + REVIEW_LADDER[Math.min(lvl, REVIEW_LADDER.length-1)]*DAY;
  const xp = 15 + 5*lvl + (overdueDays <= 0 ? 10 : 0);
  return {eternal, xp, lvl};
}
function isDue(p){ return p.sealed && !isEternal(p) && Date.now() >= (p.nextReviewAt||0); }
function sealCondition(p){
  if(!p || !p.sealed) return null;
  if(isEternal(p)) return {id:"eternal", label:"Eternal ✦", cls:"cond-eternal"};
  const od = (Date.now() - (p.nextReviewAt||0)) / DAY;
  if(od < 0)  return {id:"radiant", label:"Radiant", cls:"cond-radiant"};
  if(od < 3)  return {id:"dimming", label:"Dimming", cls:"cond-dimming"};
  if(od < 10) return {id:"fading",  label:"Fading",  cls:"cond-fading"};
  return {id:"cracked", label:"Cracked", cls:"cond-cracked"};
}
function dueReviews(){
  return VERSES
    .filter(v=>isDue(state.progress[v.id]))
    .sort((a,b)=>state.progress[a.id].nextReviewAt - state.progress[b.id].nextReviewAt);
}
function nextReviewText(p){
  if(isEternal(p)) return "Sealed forever";
  const ms = (p.nextReviewAt||0) - Date.now();
  if(ms <= 0) return "Re-seal due now";
  const d = Math.ceil(ms/DAY);
  return d === 1 ? "Re-seal in 1 day" : `Re-seal in ${d} days`;
}

function rankFor(xp){
  let r = RANKS[0][1];
  RANKS.forEach(([t,n])=>{ if(xp>=t) r=n; });
  return r;
}

/* ---- SQ registry (generated by T2 split; see ROADMAP.md §7) ---- */
SQ.isEternal = isEternal;
SQ.sealVerse = sealVerse;
SQ.resealVerse = resealVerse;
SQ.isDue = isDue;
SQ.sealCondition = sealCondition;
SQ.dueReviews = dueReviews;
SQ.nextReviewText = nextReviewText;
SQ.rankFor = rankFor;
