/* 04-review.js
   seal/re-seal/eternal, REVIEW_LADDER scheduling, due lists, RANKS
   Extracted verbatim from index.html lines 3251-3310 by T2. */
/* =========================================================
   REVIEW ENGINE — seals fade, re-seals climb the ladder
   ========================================================= */
function isEternal(p){ return p.sealed && (p.reviewLevel||0) >= REVIEW_LADDER.length; }
function sealVerse(p, grade){
  const now = Date.now();
  p.sealed = true; p.stage = 4;
  p.sealedAt = now; p.reviewLevel = 0; p.reviews = 0;
  p.srs = sm2Review(null, grade||"good", now);
  p.nextReviewAt = p.srs.dueAt;
}
function resealVerse(p, grade, opts){
  opts=opts||{};
  const now = Date.now();
  const overdueDays = (now - (p.nextReviewAt||now)) / DAY;
  if(!opts.scheduled){
    p.srs=sm2Review(p.srs,grade||"good",now);
    p.nextReviewAt=p.srs.dueAt;
  }
  const lvl=Math.min(REVIEW_LADDER.length,
    reviewLevelForStability(p.srs?.stabilityDays||0,REVIEW_LADDER));
  p.reviewLevel = lvl;
  p.reviews = (p.reviews||0) + 1;
  p.lastReviewAt = now;
  state.resealsTotal = (state.resealsTotal||0) + 1;
  const eternal = lvl >= REVIEW_LADDER.length;
  if(eternal){
    p.nextReviewAt = now + 365*DAY*50;
    p.nextPolishAt = now + ETERNAL_POLISH_DAYS*DAY;
  }
  const xp = 15 + 5*lvl + (overdueDays <= 0 ? 10 : 0);
  return {eternal, xp, lvl};
}
function isDue(p){ return p.sealed && !isEternal(p) && Date.now() >= (p.nextReviewAt||0); }
function isPolishDue(p){ return isEternal(p) && Date.now() >= (p.nextPolishAt||0); }
function sealCondition(p){
  if(!p || !p.sealed) return null;
  if(isEternal(p)) return {id:"eternal", label:"Eternal ✦", cls:"cond-eternal"};
  const od = (Date.now() - (p.nextReviewAt||0)) / DAY;
  if(od < 0)  return {id:"radiant", label:"Radiant", cls:"cond-radiant"};
  if(od < 3)  return {id:"dimming", label:"Dimming", cls:"cond-dimming"};
  if(od < 10) return {id:"fading",  label:"Fading",  cls:"cond-fading"};
  return {id:"cracked", label:"Cracked", cls:"cond-cracked"};
}
function dueReviews(){
  return activePassages()
    .filter(v=>isDue(state.progress[v.id]))
    .sort((a,b)=>state.progress[a.id].nextReviewAt - state.progress[b.id].nextReviewAt);
}
function nextReviewText(p){
  if(isEternal(p)){
    const ms=(p.nextPolishAt||0)-Date.now();
    if(ms<=0) return "Eternal · optional polish due";
    const d=Math.ceil(ms/DAY);
    return `Eternal · optional polish in ${d} day${d===1?"":"s"}`;
  }
  const ms = (p.nextReviewAt||0) - Date.now();
  if(ms <= 0) return "Re-seal due now";
  const d = Math.ceil(ms/DAY);
  return d === 1 ? "Re-seal in 1 day" : `Re-seal in ${d} days`;
}

function rankFor(xp){
  let r = RANKS[0][1];
  RANKS.forEach(([t,n])=>{ if(xp>=t) r=n; });
  return r;
}

/* ---- SQ registry (generated by T2 split; see ROADMAP.md §7) ---- */
SQ.isEternal = isEternal;
SQ.sealVerse = sealVerse;
SQ.resealVerse = resealVerse;
SQ.isDue = isDue;
SQ.isPolishDue = isPolishDue;
SQ.sealCondition = sealCondition;
SQ.dueReviews = dueReviews;
SQ.nextReviewText = nextReviewText;
SQ.rankFor = rankFor;
