/* 06-helpers.js
   tower stats, recommended verse, toast, openStudy
   Extracted verbatim from index.html lines 3428-3475 by T2. */
/* =========================================================
   HELPERS shared by views
   ========================================================= */
function versesInVolume(vol){ return VERSES.filter(v=>v.volume===vol); }
function towerStats(vol){
  const vs = versesInVolume(vol);
  let sealed=0, due=0, eternal=0;
  vs.forEach(v=>{
    const p = state.progress[v.id];
    if(p.sealed) sealed++;
    if(isDue(p)) due++;
    if(isEternal(p)) eternal++;
  });
  return {total:vs.length, sealed, due, eternal, pct: vs.length? sealed/vs.length : 0};
}
function currentFloorIndex(vol){
  const vs = versesInVolume(vol);
  const i = vs.findIndex(v=>!state.progress[v.id].sealed);
  return i === -1 ? vs.length-1 : i;
}
function recommendedVerse(){
  const inProg = VERSES.find(v=>{const p=state.progress[v.id]; return !p.sealed && (p.stage||0) > 0;});
  if(inProg) return inProg;
  const bomFirst = v => v.volume === "Book of Mormon" ? 0 : 1;
  const gs = VERSES
    .filter(v=>isPopularVerse(v) && difficultyForVerse(v).index <= 1 && !state.progress[v.id].sealed)
    .sort((a,b)=>bomFirst(a) - bomFirst(b) || difficultyForVerse(a).index - difficultyForVerse(b).index || wordCount(a.text) - wordCount(b.text));
  return gs[0] || VERSES.find(v=>!state.progress[v.id].sealed) || VERSES[0];
}
let toastTimer = null;
function showToast(msg, gold){
  const t = document.getElementById("toast");
  t.innerHTML = msg;
  t.className = "toast show" + (gold ? " gold" : "");
  clearTimeout(toastTimer);
  toastTimer = setTimeout(()=>{ t.className = "toast"; }, 3400);
}
function openStudy(verseId, reviewMode){
  view.verseId = verseId;
  view.stage = reviewMode ? 3 : state.progress[verseId].stage;
  view.blanked = new Set();
  view.editing = false;
  view.reviewMode = !!reviewMode;
  view.tab = "study";
  render();
  window.scrollTo({top:0});
}

/* ---- SQ registry (generated by T2 split; see ROADMAP.md §7) ---- */
SQ.versesInVolume = versesInVolume;
SQ.towerStats = towerStats;
SQ.currentFloorIndex = currentFloorIndex;
SQ.recommendedVerse = recommendedVerse;
Object.defineProperty(SQ,"toastTimer",{get:()=>toastTimer,set:v=>{toastTimer=v;},enumerable:true,configurable:true});
SQ.showToast = showToast;
SQ.openStudy = openStudy;
