/* 06-helpers.js
   tower stats, recommended verse, toast, openStudy
   Extracted verbatim from index.html lines 3428-3475 by T2. */
/* =========================================================
   HELPERS shared by views
   ========================================================= */
function towerStats(campaignId){
  const vs = campaignPassages(campaignId);
  let sealed=0, due=0, eternal=0;
  vs.forEach(v=>{
    const p = state.progress[v.id];
    if(p.sealed) sealed++;
    if(isDue(p)) due++;
    if(isEternal(p)) eternal++;
  });
  return {total:vs.length, sealed, due, eternal, pct: vs.length? sealed/vs.length : 0};
}
function currentCampaignFloorIndex(campaignId){
  const vs = campaignPassages(campaignId);
  const i = vs.findIndex(v=>!state.progress[v.id].sealed);
  return i === -1 ? vs.length-1 : i;
}
function recommendedVerse(){
  const passages = allPassages();
  const inProg = passages.find(v=>{const p=state.progress[v.id]; return !p.sealed && (p.stage||0) > 0;});
  if(inProg) return inProg;
  const starting = state.startingCampaignId || (activeCampaigns()[0] && activeCampaigns()[0].id);
  const startsHere = v => {
    const c = primaryCampaignForPassage(v.id, starting);
    return c && c.id === starting ? 0 : 1;
  };
  const gs = passages
    .filter(v=>isPopularVerse(v) && difficultyForVerse(v).index <= 1 && !state.progress[v.id].sealed)
    .sort((a,b)=>startsHere(a) - startsHere(b) || difficultyForVerse(a).index - difficultyForVerse(b).index || wordCount(a.text) - wordCount(b.text));
  return gs[0] || passages.find(v=>!state.progress[v.id].sealed) || passages[0];
}
let toastTimer = null;
function showToast(msg, gold){
  const t = document.getElementById("toast");
  t.innerHTML = msg;
  t.className = "toast show" + (gold ? " gold" : "");
  clearTimeout(toastTimer);
  toastTimer = setTimeout(()=>{ t.className = "toast"; }, 3400);
}
function openStudy(passageId, reviewMode){
  const campaign = primaryCampaignForPassage(passageId, view.campaignId);
  if(campaign) view.campaignId = campaign.id;
  view.passageId = passageId;
  view.stage = reviewMode ? 3 : state.progress[passageId].stage;
  view.blanked = new Set();
  view.editing = false;
  view.reviewMode = !!reviewMode;
  view.tab = "study";
  render();
  window.scrollTo({top:0});
}

/* ---- SQ registry (generated by T2 split; see ROADMAP.md §7) ---- */
SQ.towerStats = towerStats;
SQ.currentCampaignFloorIndex = currentCampaignFloorIndex;
SQ.recommendedVerse = recommendedVerse;
Object.defineProperty(SQ,"toastTimer",{get:()=>toastTimer,set:v=>{toastTimer=v;},enumerable:true,configurable:true});
SQ.showToast = showToast;
SQ.openStudy = openStudy;
