/* 07-sfx.js
   WebAudio synth — no files, no dependencies
   Extracted verbatim from index.html lines 3476-3523 by T2. */
/* =========================================================
   SFX — tiny WebAudio synth. No files, no dependencies.
   Every call checks state.sound; context is created lazily
   on the first user-gesture-driven play.
   ========================================================= */
const SFX = (function(){
  let ctx = null;
  function ac(){
    if(state.sound === false) return null;
    try{
      if(!ctx) ctx = new (window.AudioContext || window.webkitAudioContext)();
      if(ctx.state === "suspended") ctx.resume();
      return ctx;
    }catch(e){ return null; }
  }
  function tone(freq, t0, dur, type, vol, slide){
    const c = ac(); if(!c) return;
    const o = c.createOscillator(), g = c.createGain();
    o.type = type || "sine";
    o.frequency.setValueAtTime(freq, c.currentTime + t0);
    if(slide) o.frequency.exponentialRampToValueAtTime(slide, c.currentTime + t0 + dur);
    g.gain.setValueAtTime(0.0001, c.currentTime + t0);
    g.gain.exponentialRampToValueAtTime(vol || 0.12, c.currentTime + t0 + 0.012);
    g.gain.exponentialRampToValueAtTime(0.0001, c.currentTime + t0 + dur);
    o.connect(g); g.connect(c.destination);
    o.start(c.currentTime + t0);
    o.stop(c.currentTime + t0 + dur + 0.05);
  }
  return {
    tap(){ tone(660, 0, .08, "sine", .07); },
    pick(){ tone(520, 0, .07, "triangle", .09); tone(780, .05, .09, "sine", .07); },
    correct(combo){
      const base = 523.25 * Math.pow(1.059463, Math.min(12, (combo||1)-1)); // rises with combo, caps +1 octave
      tone(base, 0, .12, "sine", .12);
      tone(base*1.25, .07, .12, "sine", .11);
      tone(base*1.5, .14, .2, "sine", .1);
    },
    wrong(){ tone(196, 0, .18, "triangle", .1, 150); tone(147, .12, .22, "triangle", .08, 110); },
    seal(){ [523.25,659.25,783.99,1046.5].forEach((f,i)=> tone(f, i*.09, .34, "sine", .12)); tone(2093, .4, .5, "sine", .05); },
    chest(){ tone(120, 0, .16, "square", .06, 90); tone(220, .12, .1, "triangle", .07); },
    fanfare(){ [523.25,659.25,783.99,1046.5,1318.5].forEach((f,i)=> tone(f, i*.1, .4, "triangle", .1)); tone(1568, .55, .6, "sine", .07); },
    milestone(){ [392,523.25,659.25,783.99].forEach((f,i)=> tone(f, i*.08, .3, "sine", .11)); },
    gift(){ tone(880, 0, .3, "sine", .09, 1760); tone(1318.5, .18, .3, "sine", .08); tone(1760, .32, .4, "sine", .07); },
    whoosh(){ tone(300, 0, .25, "sine", .05, 900); },
    tick(){ tone(880, 0, .04, "square", .03); }
  };
})();

/* ---- SQ registry (generated by T2 split; see ROADMAP.md §7) ---- */
SQ.SFX = SFX;
