/* 08-fx.js
   canvas confetti bursts and celebrations
   Extracted verbatim from index.html lines 3524-3596 by T2. */
/* =========================================================
   FX — lightweight canvas confetti (bursts + celebrations)
   ========================================================= */
const FX = (function(){
  const COLORS = ["#f4b942","#fbbf24","#22d3ee","#34d399","#a78bfa","#ffffff","#fb923c"];
  let canvas = null, cx = null, parts = [], raf = null;
  const reduced = ()=> window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  function ensure(){
    if(!canvas){
      canvas = document.createElement("canvas");
      canvas.id = "fxCanvas";
      document.body.appendChild(canvas);
      cx = canvas.getContext("2d");
    }
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;
  }
  function spawn(n, x, y, spread, up){
    for(let i=0;i<n;i++){
      const a = (Math.random()*spread - spread/2) * Math.PI/180 - Math.PI/2;
      const sp = 3 + Math.random()*(up||7);
      parts.push({
        x, y,
        vx: Math.cos(a)*sp, vy: Math.sin(a)*sp,
        w: 4+Math.random()*5, h: 3+Math.random()*4,
        rot: Math.random()*Math.PI, vr: (Math.random()-.5)*.3,
        color: COLORS[Math.floor(Math.random()*COLORS.length)],
        life: 60 + Math.random()*40, round: Math.random()<.3
      });
    }
    if(!raf) loop();
  }
  function loop(){
    raf = requestAnimationFrame(()=>{
      cx.clearRect(0,0,canvas.width,canvas.height);
      parts = parts.filter(p=>p.life>0 && p.y < canvas.height+20);
      parts.forEach(p=>{
        p.x += p.vx; p.y += p.vy; p.vy += 0.22; p.vx *= .99; p.rot += p.vr; p.life -= 1;
        cx.save();
        cx.translate(p.x, p.y);
        cx.rotate(p.rot);
        cx.globalAlpha = Math.max(0, Math.min(1, p.life/30));
        cx.fillStyle = p.color;
        if(p.round){ cx.beginPath(); cx.arc(0,0,p.w/2,0,7); cx.fill(); }
        else cx.fillRect(-p.w/2, -p.h/2, p.w, p.h);
        cx.restore();
      });
      if(parts.length) loop();
      else { raf = null; cx.clearRect(0,0,canvas.width,canvas.height); }
    });
  }
  return {
    burst(x, y, opts){
      if(reduced()) return;
      ensure();
      spawn((opts&&opts.count)||26, x, y, (opts&&opts.spread)||120, (opts&&opts.power)||7);
    },
    burstAt(el, opts){
      if(!el || reduced()) return;
      const r = el.getBoundingClientRect();
      this.burst(r.left + r.width/2, r.top + r.height/2, opts);
    },
    rain(opts){
      if(reduced()) return;
      ensure();
      const n = (opts&&opts.count)||90;
      for(let i=0;i<4;i++){
        spawn(Math.ceil(n/4), canvas.width*(0.15+0.7*Math.random()), canvas.height*0.22, 160, 10);
      }
    }
  };
})();

/* ---- SQ registry (generated by T2 split; see ROADMAP.md §7) ---- */
SQ.FX = FX;
