/* 09-checkin.js
   daily check-in, journey milestones
   Extracted verbatim from index.html lines 3597-3643 by T2. */
/* =========================================================
   DAILY CHECK-IN — show up, claim the day's blessing, keep
   the habit chain alive. Claiming counts as activity.
   ========================================================= */
function hasClaimedToday(){ const d = state.calendar[localISODate()]; return !!(d && d.c); }
function claimDailyGift(){
  if(hasClaimedToday()) return null;
  calDay(localISODate()).c = 1;
  touchStreak();
  const base = 10 + Math.min(20, state.streak*2);
  const lucky = Math.random() < 0.15;
  const xp = base + (lucky ? 15 : 0);
  state.xp += xp;
  const hearts = refillArenaHearts(ARENA_HEART_MAX);
  saveState();
  return {xp, lucky, hearts};
}
function isoForDate(d){ return new Date(d.getTime() - d.getTimezoneOffset()*60000).toISOString().slice(0,10); }
function addLocalDays(d, amount){ const x = new Date(d); x.setHours(12,0,0,0); x.setDate(x.getDate()+amount); return x; }
function currentStreakStart(){
  const today = new Date(); today.setHours(12,0,0,0);
  return addLocalDays(today, -Math.max(0,(state.streak||1)-1));
}
const CHECKIN_MILESTONES = [
  {day:3,  icon:"🧰", short:"Momentum", copy:"Three sparks become a flame"},
  {day:7,  icon:"🛡️", short:"Shield", copy:"One full week protected"},
  {day:14, icon:"🎁", short:"Treasure", copy:"Two weeks of steady return"},
  {day:21, icon:"👑", short:"Crown", copy:"A strong rhythm is forming"},
  {day:28, icon:"🏆", short:"Grand chest", copy:"Four weeks faithfully built"}
];
function journeyDays(n=28){
  const start = currentStreakStart();
  const todayIso = localISODate();
  return Array.from({length:n},(_,i)=>{
    const d=addLocalDays(start,i), iso=isoForDate(d), step=i+1;
    const rec=state.calendar[iso];
    return {iso, step, dow:"SMTWTFS"[d.getDay()], isToday:iso===todayIso, isFuture:iso>todayIso, rec, milestone:CHECKIN_MILESTONES.find(m=>m.day===step)||null};
  });
}
function currentJourneyWeek(){
  const all=journeyDays(35);
  const currentStep=Math.max(1,state.streak||1);
  const chapterStart=Math.floor((currentStep-1)/7)*7;
  return all.slice(chapterStart,chapterStart+7);
}
function nextJourneyReward(){ return CHECKIN_MILESTONES.find(m=>m.day>(state.streak||0)) || null; }

/* ---- SQ registry (generated by T2 split; see ROADMAP.md §7) ---- */
SQ.hasClaimedToday = hasClaimedToday;
SQ.claimDailyGift = claimDailyGift;
SQ.isoForDate = isoForDate;
SQ.addLocalDays = addLocalDays;
SQ.currentStreakStart = currentStreakStart;
SQ.CHECKIN_MILESTONES = CHECKIN_MILESTONES;
SQ.journeyDays = journeyDays;
SQ.currentJourneyWeek = currentJourneyWeek;
SQ.nextJourneyReward = nextJourneyReward;
