/* 13-shelf.js
   the trophy room
   Extracted verbatim from index.html lines 4059-4104 by T2. */
/* =========================================================
   RELIC SHELF — the trophy room. Towers climb in YOUR order;
   the shelf keeps relics in the order of the book.
   ========================================================= */
function renderShelf(){
  const body = document.getElementById("body");
  const total = allPassages().length;
  const claimed = allPassages().filter(v=>state.progress[v.id].sealed).length;
  let html = `
    <div class="shelf-head">
      <h2>🏺 The Relic Shelf</h2>
      <p>Climb the towers in any order you like — the shelf keeps every relic in the order of the book. Watch the dark spaces fill with light, one memorized verse at a time.</p>
      <div class="shelf-count">${claimed} / ${total} relics claimed</div>
    </div>`;
  activeCampaigns().forEach(campaign=>{
    const vs = campaignPassages(campaign.id);
    const c = vs.filter(v=>state.progress[v.id].sealed).length;
    const safeCampaign=safeCampaignHTML(campaign);
    html += `
      <div class="shelf-room" style="--thue:${campaign.hue}">
        <h3><span>${safeCampaign.icon} ${safeCampaign.name}</span><span class="sr-count">${c}/${vs.length} claimed</span></h3>
        <div class="shelf-grid">
          ${vs.map((v,i)=>{
            const p = state.progress[v.id];
            const safe=safePassageHTML(v);
            const cls = p.sealed ? "claimed" : ((p.stage||0)>0 ? "waking" : "dark");
            const fl = floorOf(v, campaign.id);
            return `
              <div class="shelf-slot ${cls}" data-id="${safe.id}" title="${safe.topic}">
                <div class="ss-num">${i+1}</div>
                ${relicHTML(v, 58)}
                <div class="ss-ref">${safe.ref}</div>
                ${p.sealed
                  ? `<div class="ss-floor">${chestImg(fl||1, 15)} Floor ${fl||"?"} ${isEternal(p) ? "♾️" : (isDue(p) ? "🕯️" : "✦")}</div>`
                  : `<div class="ss-shards">${shardsFor(p)}/5 shards</div>`}
              </div>`;
          }).join("")}
        </div>
      </div>`;
  });
  html += `<footer class="hint">Tap any relic to see its verse. Dim relics are still buried — every memory stage you pass uncovers another shard.</footer>`;
  body.innerHTML = html;
  body.querySelectorAll(".shelf-slot").forEach(el=>{
    el.onclick = ()=> openRelicPop(passageById(el.dataset.id));
  });
}

/* ---- SQ registry (generated by T2 split; see ROADMAP.md §7) ---- */
SQ.renderShelf = renderShelf;
