/* 19-library.js
   library filters, cards, list
   Extracted verbatim from index.html lines 6197-6297 by T2. */
/* =========================================================
   LIBRARY
   ========================================================= */
function libraryFilters(){
  return [
    {id:"gettingStarted", label:"🌱 Getting Started"},
    {id:"due", label:"🕯️ Fading seals"},
    {id:"popular", label:"🔖 Popular"},
    {id:"easy", label:"☀️ Easy"},
    {id:"medium", label:"⛅ Medium"},
    {id:"hard", label:"🌧️ Hard"},
    {id:"challenge", label:"⛈️ Challenge"},
    {id:"impossible", label:"🌪️ Impossible"},
    {id:"unsealed", label:"🧭 Unsealed"},
    {id:"all", label:"📚 All"}
  ];
}
function versesForCurrentFilter(){
  let list = VERSES.slice();
  const f = view.filter || "gettingStarted";
  if(f === "gettingStarted"){
    return list
      .filter(v=>isPopularVerse(v) && difficultyForVerse(v).index <= 1 && !state.progress[v.id].sealed)
      .sort((a,b)=>difficultyForVerse(a).index - difficultyForVerse(b).index || wordCount(a.text) - wordCount(b.text))
      .slice(0,5);
  }
  if(f === "due") return dueReviews();
  if(f === "popular") return list.filter(isPopularVerse);
  if(f === "easy") return list.filter(v=>difficultyForVerse(v).index===0);
  if(f === "medium") return list.filter(v=>difficultyForVerse(v).index===1);
  if(f === "hard") return list.filter(v=>difficultyForVerse(v).index===2);
  if(f === "challenge") return list.filter(v=>difficultyForVerse(v).index===3);
  if(f === "impossible") return list.filter(v=>difficultyForVerse(v).index===4);
  if(f === "unsealed") return list.filter(v=>!state.progress[v.id].sealed);
  return list;
}
function filterCountText(){
  const n = versesForCurrentFilter().length;
  if(view.filter === "gettingStarted") return `${n}/5 shown`;
  return `${n} shown`;
}
function renderFilterPanelHTML(){
  return `
    <div class="filter-panel" id="filterPanel">
      <div class="filter-title"><span>Quest Path</span><span class="count">${filterCountText()}</span></div>
      <div class="filter-chips">
        ${libraryFilters().map(f=>`<button class="filter-chip ${view.filter===f.id?'active':''}" data-filter="${f.id}">${f.label}</button>`).join("")}
      </div>
    </div>`;
}
function popularBookmarkHTML(v){
  return isPopularVerse(v) ? '<div class="popular-bookmark" title="Popular / often quoted scripture">🔖</div>' : '';
}
function popularPillHTML(v){
  return isPopularVerse(v) ? '<div class="study-popular" title="Popular / often quoted scripture">🔖 Popular / often quoted</div>' : '';
}
function cardHTML(v){
  const p = state.progress[v.id];
  const diff = difficultyForVerse(v);
  return `
    <div class="card level-${diff.index} ${p.sealed ? 'sealed-card' : ''} ${isPopularVerse(v) ? 'popular-card' : ''}" data-id="${v.id}">
      ${popularBookmarkHTML(v)}
      <div class="difficulty-badge" title="${p.sealed ? 'Sealed' : `${diff.label} · ${diff.words} words`}">${p.sealed ? '✨' : diff.emoji}</div>
      <div class="ref">${v.ref}</div>
      <div class="theme">${v.theme}</div>
      <div class="stage-row">
        ${STAGES.map((s,i)=>`<div class="pip ${p.sealed?'sealed':(i<p.stage?'done':'')}"></div>`).join("")}
      </div>
      ${p.sealed ? `<div class="seal-tag">${isEternal(p) ? 'Eternal ✦' : (isDue(p) ? 'Re-seal due 🕯️' : 'Sealed ✦')}</div>` : ''}
    </div>`;
}
function renderLibrary(){
  const body = document.getElementById("body");
  const selected = versesForCurrentFilter();
  let html = "";
  if(view.filter === "gettingStarted"){
    html += `<div class="getting-started-note">🌱 <strong>Getting Started</strong> shows up to 5 short, popular scriptures so the first memorization wins feel fast and encouraging.</div>`;
  }
  if(view.filter === "due" && selected.length){
    html += `<div class="getting-started-note">🕯️ These seals are fading. A quick honest recitation restores each one and climbs its ladder toward an <strong>Eternal Seal</strong>.</div>`;
  }
  if(selected.length === 0){
    html += `<div class="empty">No scriptures match this filter yet.</div>`;
  } else {
    VOLUME_ORDER.forEach(vol=>{
      const items = selected.filter(v=>v.volume===vol);
      if(!items.length) return;
      html += `<div class="volume"><h2>${displayVolumeName(vol)}</h2><div class="verse-grid">`;
      items.forEach(v=>{ html += cardHTML(v); });
      html += `</div></div>`;
    });
  }
  body.innerHTML = html;
  body.querySelectorAll(".card").forEach(c=>{
    c.onclick = ()=>{
      const p = state.progress[c.dataset.id];
      openStudy(c.dataset.id, isDue(p));
    };
  });
}

/* ---- SQ registry (generated by T2 split; see ROADMAP.md §7) ---- */
SQ.libraryFilters = libraryFilters;
SQ.versesForCurrentFilter = versesForCurrentFilter;
SQ.filterCountText = filterCountText;
SQ.renderFilterPanelHTML = renderFilterPanelHTML;
SQ.popularBookmarkHTML = popularBookmarkHTML;
SQ.popularPillHTML = popularPillHTML;
SQ.cardHTML = cardHTML;
SQ.renderLibrary = renderLibrary;
