/* 20-text.js
   tokenize, isWord, escHTML, verse number markers
   Extracted verbatim from index.html lines 6298-6365 by T2. */
/* =========================================================
   WORD HELPERS + STUDY
   ========================================================= */
/* tokenize() and isWord() used to live here. They are now the canonical
   tokenizer in js/00-tokenize.js — see T3. tokenize() returns token OBJECTS
   now, not strings, and "is this a word" is a property of the token rather
   than a regex applied to a string. */
function escHTML(s){
  return String(s)
    .replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")
    .replace(/"/g,"&quot;").replace(/'/g,"&#39;");
}

/* ---- multi-verse number markers (e.g. "Alma 34:32–34") ----
   We only store the combined text per reference, not a per-verse
   breakdown, so verse boundaries are approximated by distributing
   sentences evenly across the verse range. Good enough to give a
   visual sense of where each verse starts; not scripture-accurate. */
function verseRangeFor(ref){
  const m = (ref||"").match(/(\d+):(\d+)[–-](\d+)$/);
  if(!m) return null;
  const start = parseInt(m[2],10), end = parseInt(m[3],10);
  if(!(end > start)) return null;
  return { start, end, count: end - start + 1 };
}
function verseNumberMarks(text, range){
  const toks = tokenize(text);
  const sentenceStarts = [];
  let atStart = true;
  toks.forEach(t=>{
    if(t.isWord){
      if(atStart){ sentenceStarts.push(t.index); atStart = false; }
    } else if(/[.!?]/.test(t.raw)){
      /* KNOWN DEFECT D1, preserved deliberately by T3 (ROADMAP.md §8, "Defects
         found in flight").
         This branch is unreachable for real passage text. Sentence-ending
         punctuation is glued to the word it follows ("earth."), so that token
         is a WORD and never reaches here; only whitespace and free-standing
         dashes do, and none of those contain .!?. So sentenceStarts is always
         [0], and every multi-verse passage renders a single verse number at
         word 0 instead of one per verse.
         The fix is one line — test t.tailPunct on word tokens — but it changes
         rendered output, and T3 is a tokenizer unification with no behaviour
         change. Fix it under its own ticket with its own before/after. */
      atStart = true;
    }
  });
  const n = range.count;
  if(sentenceStarts.length < n) return [{wordIdx:0, num:range.start}];
  const base = Math.floor(sentenceStarts.length / n), extra = sentenceStarts.length % n;
  const marks = [];
  let sentIdx = 0;
  for(let i=0; i<n; i++){
    marks.push({ wordIdx: sentenceStarts[sentIdx], num: range.start + i });
    sentIdx += base + (i < extra ? 1 : 0);
  }
  return marks;
}
function verseNumberMap(v){
  const range = verseRangeFor(v.ref);
  if(!range) return null;
  const marks = verseNumberMarks(v.text, range);
  return new Map(marks.map(m=>[m.wordIdx, m.num]));
}
function numberedVerseText(v){
  const map = verseNumberMap(v);
  if(!map) return escHTML(v.text);
  let out = "";
  tokenize(v.text).forEach(t=>{
    if(t.isWord && map.has(t.index)) out += `<sup class="vnum">${map.get(t.index)}</sup>`;
    out += escHTML(t.raw);
  });
  return out;
}

/* ---- SQ registry (generated by T2 split; see ROADMAP.md §7) ---- */
SQ.escHTML = escHTML;
SQ.verseRangeFor = verseRangeFor;
SQ.verseNumberMarks = verseNumberMarks;
SQ.verseNumberMap = verseNumberMap;
SQ.numberedVerseText = numberedVerseText;
