/* 20-text.js
   tokenize, isWord, escHTML, verse number markers
   Extracted verbatim from index.html lines 6298-6365 by T2. */
/* =========================================================
   WORD HELPERS + STUDY
   ========================================================= */
function tokenize(text){ return text.split(/(\s+)/).filter(t=>t.length); }
function isWord(tok){ return /\w/.test(tok); }
function escHTML(s){
  return String(s)
    .replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")
    .replace(/"/g,"&quot;").replace(/'/g,"&#39;");
}

/* ---- multi-verse number markers (e.g. "Alma 34:32–34") ----
   We only store the combined text per reference, not a per-verse
   breakdown, so verse boundaries are approximated by distributing
   sentences evenly across the verse range. Good enough to give a
   visual sense of where each verse starts; not scripture-accurate. */
function verseRangeFor(ref){
  const m = (ref||"").match(/(\d+):(\d+)[–-](\d+)$/);
  if(!m) return null;
  const start = parseInt(m[2],10), end = parseInt(m[3],10);
  if(!(end > start)) return null;
  return { start, end, count: end - start + 1 };
}
function verseNumberMarks(text, range){
  const toks = tokenize(text);
  const sentenceStarts = [];
  let wIdx = 0, atStart = true;
  toks.forEach(tok=>{
    if(isWord(tok)){
      if(atStart){ sentenceStarts.push(wIdx); atStart = false; }
      wIdx++;
    } else if(/[.!?]/.test(tok)){
      atStart = true;
    }
  });
  const n = range.count;
  if(sentenceStarts.length < n) return [{wordIdx:0, num:range.start}];
  const base = Math.floor(sentenceStarts.length / n), extra = sentenceStarts.length % n;
  const marks = [];
  let sentIdx = 0;
  for(let i=0; i<n; i++){
    marks.push({ wordIdx: sentenceStarts[sentIdx], num: range.start + i });
    sentIdx += base + (i < extra ? 1 : 0);
  }
  return marks;
}
function verseNumberMap(v){
  const range = verseRangeFor(v.ref);
  if(!range) return null;
  const marks = verseNumberMarks(v.text, range);
  return new Map(marks.map(m=>[m.wordIdx, m.num]));
}
function numberedVerseText(v){
  const map = verseNumberMap(v);
  if(!map) return escHTML(v.text);
  const toks = tokenize(v.text);
  let wIdx = 0, out = "";
  toks.forEach(tok=>{
    if(isWord(tok)){
      if(map.has(wIdx)) out += `<sup class="vnum">${map.get(wIdx)}</sup>`;
      out += escHTML(tok);
      wIdx++;
    } else {
      out += escHTML(tok);
    }
  });
  return out;
}

/* ---- SQ registry (generated by T2 split; see ROADMAP.md §7) ---- */
SQ.tokenize = tokenize;
SQ.isWord = isWord;
SQ.escHTML = escHTML;
SQ.verseRangeFor = verseRangeFor;
SQ.verseNumberMarks = verseNumberMarks;
SQ.verseNumberMap = verseNumberMap;
SQ.numberedVerseText = numberedVerseText;
